export const dataNamesMock = [
    {
        id: 1,
        name: 'Data 1',
        isDemo: false,
    },
    {
        id: 2,
        name: 'Data 2',
        isDemo: false,
    },
    {
        id: 3,
        name: 'Data 1',
        isDemo: false,
    },
    {
        id: 4,
        name: 'Data 1',
        isDemo: false,
    },
    {
        id: 5,
        name: 'Data 1',
        isDemo: true,
    },
    {
        id: 6,
        name: 'Data 1',
        isDemo: false,
    },
    {
        id: 7,
        name: 'Data 1',
        isDemo: false,
    },
    {
        id: 8,
        name: 'Data 1',
        isDemo: false,
    },
];

export const selectedDataMock = [
    {
        feature: 'Gender',
        type: 'Categorical',
        mode: 'Male',
        min: '0',
        max: '0',
        average: '72',
        missing: '0',
        sensitive: 'no',
        id: 1,
    },
    {
        feature: 'Gender',
        type: 'Categorical',
        mode: 'Male',
        min: '0',
        max: '0',
        average: '72',
        missing: '0',
        sensitive: 'no',
        id: 2,
    },
    {
        feature: 'Gender',
        type: 'Categorical',
        mode: 'Male',
        min: '0',
        max: '0',
        average: '72',
        missing: '0',
        sensitive: 'no',
        id: 3,
    },
    {
        feature: 'Gender',
        type: 'Categorical',
        mode: 'Male',
        min: '0',
        max: '0',
        average: '72',
        missing: '0',
        sensitive: 'no',
        id: 4,
    },
    {
        feature: 'Gender',
        type: 'Categorical',
        mode: 'Male',
        min: '0',
        max: '0',
        average: '72',
        missing: '0',
        sensitive: 'no',
        id: 5,
    },
    {
        feature: 'Gender',
        type: 'Categorical',
        mode: 'Male',
        min: '0',
        max: '0',
        average: '72',
        missing: '0',
        sensitive: 'no',
        id: 6,
    },
    {
        feature: 'Gender',
        type: 'Categorical',
        mode: 'Male',
        min: '0',
        max: '0',
        average: '72',
        missing: '0',
        sensitive: 'no',
        id: 7,
    },
    {
        feature: 'Gender',
        type: 'Categorical',
        mode: 'Male',
        min: '0',
        max: '0',
        average: '72',
        missing: '0',
        sensitive: 'no',
        id: 8,
    },
    {
        feature: 'Gender',
        type: 'Categorical',
        mode: 'Male',
        min: '0',
        max: '0',
        average: '72',
        missing: '0',
        sensitive: 'no',
        id: 9,
    },
    {
        feature: 'Gender',
        type: 'Categorical',
        mode: 'Male',
        min: '0',
        max: '0',
        average: '72',
        missing: '0',
        sensitive: 'no',
        id: 10,
    },
    {
        feature: 'Gender',
        type: 'Categorical',
        mode: 'Male',
        min: '0',
        max: '0',
        average: '72',
        missing: '0',
        sensitive: 'no',
        id: 11,
    },
];
// TODO delete this file when connect to backend
