name: Deploy to development

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_DEV_REGION }}
      CF_DIST_ID: ${{ secrets.CF_DEV_DIST_ID }}
      S3_BUCKET_NAME: ${{ secrets.S3_DEV_BUCKET_NAME }}
      # APP ENV VARS
      APP_API_URL: ${{ secrets.APP_DEV_API_URL }}

    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: "Install dependencies"
        run: yarn install

      - name: "Start build process"
        run: yarn build:prod

      - name: "Start deploy process"
        run: yarn deploy
